language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer install

script:
 - mkdir -p build/logs
 - mkdir -p cache
 - chown -R travis:travis cache/
 - phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls